---
- name: copy config bind
  template:
    src: templates/slave.named.conf.default-zones
    dest: /etc/bind/named.conf.default-zones
    owner: root
    group: bind
    mode: 0640

- name: copy config bind
  template:
    src: templates/slave.named.conf.options
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0640

- name: copy resolv.conf to the server
  template: 
    src: templates/servers-resolv.conf 
    dest: /etc/resolv.conf 
    owner: root 
    group: root
    mode: 0644

- name: Create a directory for slaves zone
  file:
    path: /etc/bind/slaves
    state: directory
    owner: root
    group: bind
    mode: '0640'

- name: set /etc/bind permissions
  file:
    path: /etc/bind
    owner: root
    group: bind
    mode: 0670

- name: ensure bind is running and enabled
  service: 
    name: bind9
    state: restarted
    enabled: yes
