---
- name: install bind
  apt:
    name:
      - bind9
      - bind9utils
      - bind9-doc
    state: latest
    update_cache: true
  when: inventory_hostname in groups["servers"]

- name: start chronyd
  service: 
    name: chronyd
    state: restarted
    enabled: true
